[items]
"../graphics/excavation/items/heart_scale.4bpp" = "ITEMID_HEART_SCALE"
"../graphics/excavation/items/star_piece.4bpp" = "ITEMID_STAR_PIECE"
"../graphics/excavation/items/red_shard.4bpp" = "ITEMID_RED_SHARD"
"../graphics/excavation/items/revive.4bpp" = "ITEMID_REVIVE"
"../graphics/excavation/items/shoal_shell.4bpp" = "ITEMID_SHOAL_SHELL"
"../graphics/excavation/items/shoal_salt.4bpp" =  "ITEMID_SHOAL_SALT"
"../graphics/excavation/items/pearl.4bpp" = "ITEMID_PEARL"
"../graphics/excavation/items/blue_shard.4bpp" = "ITEMID_BLUE_SHARD"
"../graphics/excavation/items/big_pearl.4bpp" = "ITEMID_BIG_PEARL"
"../graphics/excavation/items/ever_stone.4bpp" = "ITEMID_EVERSTONE"
"../graphics/excavation/items/hard_stone.4bpp" = "ITEMID_HARD_STONE"
"../graphics/excavation/items/revive_max.4bpp" = "ITEMID_MAX_REVIVE"
"../graphics/excavation/items/nugget.4bpp" = "ITEMID_NUGGET"
"../graphics/excavation/items/yellow_shard.4bpp" = "ITEMID_YELLOW_SHARD"
"../graphics/excavation/items/green_shard.4bpp" = "ITEMID_GREEN_SHARD"
"../graphics/excavation/items/leaf_stone.4bpp" = "ITEMID_LEAF_STONE"
"../graphics/excavation/items/fire_stone.4bpp" = "ITEMID_FIRE_STONE"
"../graphics/excavation/items/water_stone.4bpp" = "ITEMID_WATER_STONE"
"../graphics/excavation/items/thunder_stone.4bpp" = "ITEMID_THUNDER_STONE"
"../graphics/excavation/items/moon_stone.4bpp" = "ITEMID_MOON_STONE"
"../graphics/excavation/items/sun_stone.4bpp" = "ITEMID_SUN_STONE"
"../graphics/excavation/items/root_fossil.4bpp" = "ITEMID_ROOT_FOSSIL"
"../graphics/excavation/items/claw_fossil.4bpp" = "ITEMID_CLAW_FOSSIL"

[stones]
"../graphics/excavation/stones/stone_2x2.4bpp" = "ID_STONE_2x2"
"../graphics/excavation/stones/stone_3x3.4bpp" = "ID_STONE_3x3"
"../graphics/excavation/stones/stone_1x4.4bpp" = "ID_STONE_1x4"
"../graphics/excavation/stones/stone_4x1.4bpp" = "ID_STONE_4x1"
"../graphics/excavation/stones/stone_2x4.4bpp" = "ID_STONE_2x4"
"../graphics/excavation/stones/stone_4x2.4bpp" = "ID_STONE_4x2"
"../graphics/excavation/stones/stone_snake1.4bpp" = "ID_STONE_SNAKE1"
"../graphics/excavation/stones/stone_snake2.4bpp" = "ID_STONE_SNAKE2"
"../graphics/excavation/stones/stone_mushroom1.4bpp" = "ID_STONE_MUSHROOM1"
"../graphics/excavation/stones/stone_mushroom2.4bpp" = "ID_STONE_MUSHROOM2"
